#!/usr/bin/env ruby

#require 'llms'
require_relative '../lib/llms'

executor = LLMs::Executors.instance(
  model_name: 'claude-sonnet-4-0',
  temperature: 0.0,
  max_completion_tokens: 1000
)

puts executor.execute_prompt("What is 2+2?")
